### ISSUE TITLE
Refresh issue

### ISSUE THREAD

**Issue by Adnan0061** [RoBYCoNTe/superset-dashboard#3]
Hi, great package.
I am facing an issue. In the superset dashboard, I have set an auto-refresh interval; in the superset, the dashboard is refreshing according to the interval. But in the embedded dashboard it's not auto-refreshing. How can I solve this issue?

**Comment by RoBYCoNTe** [comment]
Hi, can you be more specific? Have you checked Developer Tools to ensure that nothing is wrong inside Superset?

**Comment by Adnan0061** [comment]
Hi, yeah I checked superset. inside superset dashboards are refreshing. Also in the public role, these permissions are given. 
![image](https://github.com/RoBYCoNTe/superset-dashboard-sdk/assets/48943431/6f9ecfbf-2467-4913-bd69-834ac024459d)

But in the embedded dashboard it's not refreshing. can you check from your side, please?

**Comment by RoBYCoNTe** [comment]
Right now I'm not able to simulate this behavior, I'm not working anymore with superset dashboards nor I've a valid environment to run and execute it :(

**Comment by Adnan0061** [comment]
ok.
