### ISSUE TITLE
Unable to send url params in sdk

### ISSUE THREAD

**Issue by sundar68** [RoBYCoNTe/superset-dashboard#6]
There is one future missing in the sdk. I am unable to pass url-params, which is possible in main sdk https://www.npmjs.com/package/@superset-ui/embedded-sdk?activeTab=code 

Is there a way we can do it in "superset-dashboard-sdk".

Here is the example how we are passing in main sdk:

```

import { embedDashboard } from "@superset-ui/embedded-sdk";

embedDashboard({
  id: "abc123", // given by the Superset embedding UI
  supersetDomain: "https://superset.example.com",
  mountPoint: document.getElementById("my-superset-container"), // any html element that can contain an iframe
  fetchGuestToken: () => fetchGuestTokenFromBackend(),
  dashboardUiConfig: { // dashboard UI config: hideTitle, hideTab, hideChartControls, filters.visible, filters.expanded (optional), urlParams (optional)
      hideTitle: true,
      filters: {
          expanded: true,
      },
      urlParams: {
          foo: 'value1',
          bar: 'value2',
          // ...
      }
  },
    // optional additional iframe sandbox attributes
  iframeSandboxExtras: ['allow-top-navigation', 'allow-popups-to-escape-sandbox']
});

```

**Comment by RoBYCoNTe** [comment]
Hi @sundar68,
you can edit my plugin and submit a pull request, I will check it quickly as possible.
Right now I've no time to handle more changes to this project but I can accept any pull request (previous check).

**Comment by sundar68** [comment]
Hi @RoBYCoNTe 
Unable to create PR, remote:
```
Permission to RoBYCoNTe/superset-dashboard-sdk.git denied to sundar68.
fatal: unable to access 'https://github.com/RoBYCoNTe/superset-dashboard-sdk.git/': The requested URL returned error: 403
```

**Comment by RoBYCoNTe** [comment]
Hi @sundar68,
You have to fork project, apply your changes and then create a PR to mine. 

You cannot directly edit my repo.

**Comment by sundar68** [comment]
@RoBYCoNTe 
Please check the PR 
https://github.com/RoBYCoNTe/superset-dashboard-sdk/pull/7

If PR is fine, is it possible have changes by sunday?
have some dependency on this.

**Comment by RoBYCoNTe** [comment]
Thanks @sundar68, PR approved.
